- name: partion + mountage disk
  hosts: [servers]
  gather_facts: yes
  become: true
  become_method: sudo

  vars_files:

         # - defaults/main.yml

  tasks:


           - name: Create a new primary partition with a size 32Gib
             parted:
                device: /dev/sdc
                number: 1
                state: present


           - name: Creates directory
             file:
                path: /datadrive
                state: directory


           - name: Create a ext4 filesystem on /dev/sdc1 and check disk blocks
             filesystem:
                fstype: ext4
                dev: /dev/sdc1
                opts: -cc

           - name: Mount up device
             mount:
                path: /datadrive
                src: /dev/sdc1
                fstype: ext4
                state: present


           - name: Mount
             command: mount /dev/sdc1 /datadrive



           - name: Example of looping over a REMOTE command result
             shell: lsblk -no UUID /dev/sdc1
             register: command_result


           - name: Mount up device by UUID
             mount:
                path: /datadrive
                src: UUID={{ item }}
                fstype: ext4
                opts: defaults
                state: present
             with_items:
                     - "{{ command_result.stdout_lines }}"

